export enum UserPermission {
  CREATE_USER = "CREATE_USER",
  READ_USER = "READ_USER",
  UPDATE_USER = "UPDATE_USER",
  DELETE_USER = "DELETE_USER",
  DIMOND = "DIMOND",
  ADMIN = "ADMIN",
}

export enum WorkerPrmission {
  CREATE_WORKER = "CREATE_WORKER",
  READ_WORKER = "READ_WORKER",
  UPDATE_WORKER = "UPDATE_WORKER",
  DELETE_WORKER = "DELETE_WORKER",
  WORKER = "WORKER",
}

export enum CustomerPermission {
  CREATE_CUSTOMER = "CREATE_CUSTOMER",
  READ_CUSTOMER = "READ_CUSTOMER",
  UPDATE_CUSTOMER = "UPDATE_CUSTOMER",
  DELETE_CUSTOMER = "DELETE_CUSTOMER",
  CUSTOMER = "CUSTOMER",
}
