export enum WorkerCategory {
  MASON = "MASON",
  CONSTRUCTION_HELPER = "CONSTRUCTION_HELPER",
  CONSTRUCTION_FOREMAN = "CONSTRUCTION_FOREMAN",
  PAINTER = "PAINTER",
  CARPENTER = "CARPENTER",
  WOODWORKER = "WOODWORKER",
}
